version: '3.9'
services:
  database:
    image: postgres:14
    container_name: user_database
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: user_domain
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5434:5432"

volumes:
  postgres-data:
